#!/usr/bin/env python3
BUILD_VERSION = 36
BUILD_TAG = 'v36-fg4-dec2-driver-hud-golden-replay'
LOGGER_FORMAT_VERSION = 17
KALMAN_API_VERSION = 4
IMM_API_VERSION = 3
FUTURE_GAP_API_VERSION = 4
ANDROID_PROTOCOL_VERSION = 19

COORDINATE_X_ORIGIN = 'ego_front_bumper_display_reference'
EGO_DISPLAY_LENGTH_M = 4.8
EGO_DISPLAY_CENTER_X_M = -EGO_DISPLAY_LENGTH_M / 2.0
OBJECT_X_ADJUSTMENT_M = 0.0
