#!/usr/bin/env python3
BUILD_VERSION = 51
BUILD_TAG = 'v51r4-v50r1-can-deadline-collector10-autolc10hz-sidevision-shadow-runtimefix-perf'
LOGGER_FORMAT_VERSION = 25
KALMAN_API_VERSION = 4
IMM_API_VERSION = 3
FUTURE_GAP_API_VERSION = 15
ANDROID_PROTOCOL_VERSION = 21
SIDE_VISION_API_VERSION = 2

COORDINATE_X_ORIGIN = 'ego_front_bumper_display_reference'
EGO_DISPLAY_LENGTH_M = 4.8
EGO_DISPLAY_CENTER_X_M = -EGO_DISPLAY_LENGTH_M / 2.0
OBJECT_X_ADJUSTMENT_M = 0.0
